apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    path: charts/kube-prometheus-stack/crds
    targetRevision: 45.6.0
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
