apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/alertmanager"