apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/alertmanager"
  claimRef:
    namespace: monitoring
    name: storage-prometheus-alertmanager-0