apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-n8n
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /storage/n8n
