grafana:
  persistence:
    enabled: true
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  adminPassword: "admin"

  service:
    type: NodePort
    nodePort: 32200

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter:
        file: dashboards/node-exporter-fixed.json

  sidecar:
    dashboards:
      enabled: true
      # Scan for changed dashboards every 30s
      SCProvider: true
      # Label that config maps with dashboards should have to be recognized
      label: grafana_dashboard
      # Folder where to scan for dashboard files
      folder: /var/lib/grafana/dashboards
      # Default folder name
      defaultFolderName: default
      # Search configmaps in all namespaces
      searchNamespace: ALL
