apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .repoURL }}
    chart: {{ .chart }}
    targetRevision: {{ .targetRevision }}
    helm:
{{- if .valueFiles }}
      valueFiles:
{{ toYaml .valueFiles | indent 8 }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true