prometheus:
  server:
    retention: 7d
    persistentVolume:
      enabled: true
      storageClass: local-storage
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    service:
      type: NodePort
      nodePort: 30090
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    storageClass: local-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi


pushgateway:
  enabled: false

extraScrapeConfigs: []