alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClass: local-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi

server:
  persistentVolume:
    enabled: true
    storageClass: local-storage
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  service:
    type: NodePort
    nodePort: 30090

pushgateway:
  enabled: false

extraScrapeConfigs: []