prometheus:
  name: prometheus
  namespace: monitoring
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: prometheus
  targetRevision: 25.18.0
  valueFiles: []  # Or list values files if you want to use custom ones