apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NATICH/demo.git
    targetRevision: HEAD
    path: argocd-manifests/argo-cd/app-templates/prometheus
    helm:
      parameters:
        - name: name
          value: prometheus
        - name: chart
          value: prometheus-community/prometheus
        - name: namespace
          value: monitoring
        - name: valuesFile
          value: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true